baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lambda Days'
theme = 'hugo-book'

[params]
  BookSection = 'content'
  BookSearch = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  mounts = [
    { source = "content/attachments", target = "static/attachments" },
  ]
